# Generated by Django 4.1.5 on 2023-01-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='cnic',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='form',
            name='monthly_income',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='form',
            name='whatsapp',
            field=models.CharField(max_length=256),
        ),
    ]
